name: Run Convert to Hosts Script

on:
  push:
    branches:
      - main  # Change this to your default branch if necessary
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  run-script:
    runs-on: ubuntu-latest  # Choose the operating system for the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.10'  # Specify the Python version you need

    - name: Install Requests Module
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Convert to Hosts Script
      run: python convert_to_hosts.py  # Execute your Python script

    - name: Upload Hosts File
      uses: actions/upload-artifact@v2
      with:
        name: hosts-file
        path: hosts.txt  # Specify the path to the generated hosts file
