name: Run Convert to Hosts Script

on:
  push:
    branches:
      - main  # Ensure this matches your default branch
  workflow_dispatch:  # Allows manual trigger of the workflow
  schedule:
    - cron: '0 0 * * *'  # This schedules the workflow to run at 12:00 AM UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest  # Choose the operating system for the runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4  # Checks out the repository code

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.13'  # Use a stable version like 3.9, 3.10, or 3.11

    - name: Install Requests Module
      run: |
        python -m pip install --upgrade pip
        pip install requests

    - name: Run Convert to Hosts Script
      run: python convert_to_hosts.py  # Execute your Python script

    - name: Commit and Push hosts.txt
      run: |
        git config --local user.email "krispiriva@toke.com"  # Replace with your email
        git config --local user.name "KrispiRiva"  # Replace with your name
        git add hosts.txt
        git commit -m "Update hosts.txt" || echo "No changes to commit"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Automatically provided by GitHub Actions

    - name: Upload Hosts File
      uses: actions/upload-artifact@v4
      with:
        name: hosts-file
        path: hosts.txt  # Specify the path to the generated hosts file
